# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.5'

services:
  picpaylite:
    image: picpaylite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5048:5048
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db
    networks:
      - appnetwork
    
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: picpaylite_db
    ports:
      - 5432:5432
    networks:
      - appnetwork
    volumes:
      - postgres_volume:/var/lib/docker/volumes/postgres_volume/_data

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - appnetwork

networks:
  appnetwork:
    name: custom_network
    external: true  

volumes:
  postgres_volume:
    external: true

