# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  picpaylite:
    image: picpaylite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5048:5048
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: picpaylite_db
    ports:
      - 5432:5432
